# domain_extractor.py

"""
Provides extract_domain_name(), which maps a window title to a known web service name.
"""

DOMAIN_RULES = [
    # --- Social Media & Communication ---
    ("YouTube", ["youtube.com", "youtu.be", "youtube"]),
    ("Facebook", ["facebook.com", "fb.com", "facebook"]),
    ("Twitter", ["twitter.com", "x.com", "twitter", "t.co"]),
    ("Instagram", ["instagram.com", "instagram"]),
    ("LinkedIn", ["linkedin.com", "linkedin"]),
    ("Snapchat", ["snapchat.com", "snapchat"]),
    ("TikTok", ["tiktok.com", "tiktok"]),
    ("Reddit", ["reddit.com", "reddit", "r/"]),
    ("Telegram", ["telegram.org", "telegram"]),
    ("WhatsApp", ["whatsapp.com", "web.whatsapp.com", "whatsapp"]),
    ("WeChat", ["wechat.com", "weixin.qq.com", "wechat"]),
    ("Quora", ["quora.com", "quora"]),
    # --- Entertainment & Streaming ---
    ("Netflix", ["netflix.com", "netflix"]),
    ("Amazon Prime Video", ["primevideo.com", "amazon prime", "prime video"]),
    ("Hotstar", ["hotstar.com", "hotstar"]),
    ("Twitch", ["twitch.tv", "twitch"]),
    ("Spotify", ["spotify.com", "spotify"]),
    ("YouTube Music", ["music.youtube.com", "ytmusic"]),
    ("SoundCloud", ["soundcloud.com", "soundcloud"]),
    ("JioCinema", ["jiocinema.com", "jiocinema"]),
    ("Disney+", ["disneyplus.com", "disney+"]),
    ("Hulu", ["hulu.com", "hulu"]),
    ("Crunchyroll", ["crunchyroll.com", "crunchyroll"]),
    ("Gaana", ["gaana.com", "gaana"]),
    ("Wynk Music", ["wynk.in", "wynk"]),
    ("MX Player", ["mxplayer.in", "mx player"]),
    # AI Platforms / Chatbots / Generative AI
    ("ChatGPT", ["chat.openai.com", "openai.com", "chatgpt"]),
    ("OpenAI", ["openai.com"]),
    ("Claude", ["claude.ai", "anthropic.com"]),
    ("Google Gemini", ["gemini.google.com", "bard.google.com", "bard"]),
    ("Perplexity AI", ["perplexity.ai"]),
    ("Character AI", ["character.ai"]),
    ("Hugging Face", ["huggingface.co", "huggingface"]),
    ("GitHub Copilot", ["copilot.github.com", "github copilot"]),
    ("Quora Poe", ["poe.com"]),
    ("Replika AI", ["replika.ai", "replika"]),
    ("Grok AI", ["grok.com", "grok"]),
    ("Jasper AI", ["jasper.ai"]),
    ("Writesonic", ["writesonic.com"]),
    ("You AI", ["you.com", "you.com/chat"]),
    ("DeepL Write", ["deepl.com/write", "deepl write"]),
    ("Copy AI", ["copy.ai"]),
    ("Rytr AI", ["rytr.me"]),
    ("Notion AI", ["notion.so/ai", "notion ai"]),
    ("Socratic", ["socratic.org", "socratic"]),
    ("AI Dungeon", ["aidungeon.io", "ai dungeon"]),
    # --- Shopping & Marketplaces ---
    ("Amazon", ["amazon.com", "amazon"]),
    ("Flipkart", ["flipkart.com", "flipkart"]),
    ("eBay", ["ebay.com", "ebay"]),
    ("AliExpress", ["aliexpress.com", "aliexpress"]),
    ("Myntra", ["myntra.com", "myntra"]),
    ("Shein", ["shein.com", "shein"]),
    ("Nykaa", ["nykaa.com", "nykaa"]),
    ("Meesho", ["meesho.com", "meesho"]),
    # --- Productivity & Work ---
    ("Gmail", ["gmail.com", "mail.google.com", "gmail"]),
    ("Google Drive", ["drive.google.com", "gdrive"]),
    ("Google Docs", ["docs.google.com", "gdocs"]),
    ("Slack", ["slack.com", "slack"]),
    ("Zoom", ["zoom.us", "zoom"]),
    ("Notion", ["notion.so", "notion"]),
    ("Trello", ["trello.com", "trello"]),
    ("Dropbox", ["dropbox.com", "dropbox"]),
    # --- Developer / Coding Platforms ---
    ("StackOverflow", ["stackoverflow.com", "stackoverflow"]),
    ("GitHub", ["github.com", "github"]),
    ("GitLab", ["gitlab.com", "gitlab"]),
    ("Replit", ["replit.com", "replit"]),
    ("HackerRank", ["hackerrank.com", "hackerrank"]),
    ("LeetCode", ["leetcode.com", "leetcode"]),
    ("GeeksforGeeks", ["geeksforgeeks.org", "gfg"]),
    ("CodePen", ["codepen.io", "codepen"]),
    ("JSFiddle", ["jsfiddle.net", "jsfiddle"]),
    ("W3Schools", ["w3schools.com", "w3schools"]),
    ("Coursera", ["coursera.org", "coursera"]),
    ("Udemy", ["udemy.com", "udemy"]),
    ("edX", ["edx.org", "edx"]),
    ("FreeCodeCamp", ["freecodecamp.org", "freecodecamp"]),
    # --- Search Engines ---
    ("Google", ["google.com"]),
    ("Bing", ["bing.com", "bing"]),
    ("DuckDuckGo", ["duckduckgo.com", "duckduckgo"]),
    ("Yahoo", ["yahoo.com", "yahoo"]),
    ("Yandex", ["yandex.com", "yandex"]),
    ("Baidu", ["baidu.com", "baidu"]),
    # --- News & Forums ---
    ("Medium", ["medium.com", "medium"]),
    ("BBC", ["bbc.com", "bbc"]),
    ("CNN", ["cnn.com", "cnn"]),
    ("Hacker News", ["news.ycombinator.com", "hacker news"]),
    ("4chan", ["4chan.org", "4chan"]),
    ("9GAG", ["9gag.com", "9gag"]),
    # --- Meme & Geek/Niche Sites ---
    ("Imgur", ["imgur.com", "imgur"]),
    ("KnowYourMeme", ["knowyourmeme.com", "knowyourmeme"]),
    ("Memedroid", ["memedroid.com", "memedroid"]),
    ("XKCD", ["xkcd.com", "xkcd"]),
    ("Explosm", ["explosm.net", "cyanide and happiness"]),
    # --- Anime / Gaming / Otaku Stuff ---
    ("Crunchyroll", ["crunchyroll.com"]),
    ("Funimation", ["funimation.com"]),
    ("MyAnimeList", ["myanimelist.net"]),
    ("AniList", ["anilist.co"]),
    ("Steam", ["store.steampowered.com", "steamcommunity.com"]),
    ("Epic Games", ["epicgames.com"]),
    ("Roblox", ["roblox.com"]),
    ("Minecraft", ["minecraft.net", "minecraft"]),
    ("League of Legends", ["leagueoflegends.com", "lol"]),
    ("Valorant", ["playvalorant.com", "valorant"]),
    ("Fortnite", ["fortnite.com", "fortnite"]),
    ("PUBG", ["pubg.com", "pubgmobile.com"]),
    # --- Torrent Trackers ---
    ("1337x", ["1337x.to"]),
    ("The Pirate Bay", ["thepiratebay.org"]),
    ("RARBG", ["rarbg.to"]),
    ("YTS", ["yts.mx"]),
    ("LimeTorrents", ["limetorrents.info"]),
    ("TorrentGalaxy", ["torrentgalaxy.to"]),
    ("Kickass Torrents", ["katcr.to"]),
    # --- Dark Web / Onion (Optional) ---
    ("Tor Project", ["torproject.org"]),
    ("ProtonMail", ["proton.me", "protonmail.com"]),
    ("DuckDuckGo", ["duckduckgo.com"]),
    ("Brave Browser", ["brave.com"]),
    ("Tails OS", ["tails.boum.org"]),
    ("DuckDuckGo Onion", ["3g2upl4pq6kufc4m.onion", "duckduckgo onion"]),
    # Crypto / Web3 / Blockchain / NFT / DeFi Platforms
    ("Binance", ["binance.com", "binance"]),
    ("Coinbase", ["coinbase.com", "coinbase"]),
    ("CoinMarketCap", ["coinmarketcap.com", "coinmarketcap"]),
    ("CoinGecko", ["coingecko.com", "coingecko"]),
    ("Trust Wallet", ["trustwallet.com", "trust wallet"]),
    ("MetaMask", ["metamask.io", "metamask"]),
    ("Blockchain.com", ["blockchain.com", "blockchain wallet"]),
    ("Kraken", ["kraken.com", "kraken crypto"]),
    ("KuCoin", ["kucoin.com", "kucoin"]),
    ("OKX", ["okx.com", "okx"]),
    ("Gate.io", ["gate.io", "gateio"]),
    ("Bybit", ["bybit.com", "bybit"]),
    ("Bitfinex", ["bitfinex.com", "bitfinex"]),
    ("Crypto.com", ["crypto.com"]),
    ("Uniswap", ["uniswap.org", "uniswap"]),
    ("PancakeSwap", ["pancakeswap.finance", "pancakeswap"]),
    ("Opensea", ["opensea.io", "opensea"]),
    ("Rarible", ["rarible.com", "rarible"]),
    ("Etherscan", ["etherscan.io", "etherscan"]),
    ("Dune Analytics", ["dune.com", "dune analytics"]),
    ("Phantom Wallet", ["phantom.app", "phantom wallet"]),
    ("Solscan", ["solscan.io", "solscan"]),
    ("LooksRare", ["looksrare.org", "looksrare"]),
    ("Magic Eden", ["magiceden.io", "magic eden"]),
    ("DefiLlama", ["defillama.com", "defillama"]),
    ("Ledger", ["ledger.com", "ledger wallet"]),
    ("Trezor", ["trezor.io", "trezor wallet"]),
    ("Zapper", ["zapper.xyz", "zapper"]),
    ("Blur NFT", ["blur.io", "blur nft"]),
    # --- Adult Content Filters (Famous Only) ---
    ("Pornhub", ["pornhub.com", "pornhub"]),
    ("XVideos", ["xvideos.com", "xvideos"]),
    ("XNXX", ["xnxx.com", "xnxx"]),
    ("OnlyFans", ["onlyfans.com", "onlyfans"]),
    ("RedTube", ["redtube.com", "redtube"]),
    ("Brazzers", ["brazzers.com", "brazzers"]),
    ("YouPorn", ["youporn.com", "youporn"]),
    ("SpankBang", ["spankbang.com", "spankbang"]),
    ("Chaturbate", ["chaturbate.com", "chaturbate"]),
    ("BangBros", ["bangbros.com", "bangbros"]),
    ("RealityKings", ["realitykings.com", "realitykings"]),
    ("NaughtyAmerica", ["naughtyamerica.com", "naughtyamerica"]),
    ("XHamster", ["xhamster.com", "xhamster"]),
    ("CamSoda", ["camsoda.com", "camsoda"]),
    ("Stripchat", ["stripchat.com", "stripchat"]),
    ("Fansly", ["fansly.com", "fansly"]),
]


def extract_domain_name(window_title: str) -> str | None:
    """
    Scan the window title against known domain patterns and return the service name.
    Returns None if no match is found.
    """
    title = window_title.lower()
    for name, patterns in DOMAIN_RULES:
        for pat in patterns:
            if pat in title:
                return name
    return None
