def load_image_map():
    return {
        "msedge": "edge_icon",
        "chrome": "chrome_icon",
        "opera": "opera_icon",
        "brave": "brave_icon",
        "firefox": "firefox_icon",
        "notepad": "notepad_icon",
        "google": "google_icon",
        "notepad++": "notepad_icon",
        "discord": "discord_icon",
        "explorer": "file_explorer_icon",
        "spotify": "spotify_icon",
        "code": "vscode_icon",
        "slack": "slack_icon",
        "microsoftstore": "store_icon",
        "settings": "settings_icon",
        "olk": "outlook_icon",
        "wmplayer": "media_player_icon",
        "clipchamp": "clipchamp_icon",
        "xbox": "xbox_icon",
        "steamwebhelper": "steam_icon",
        "epicgameslauncher": "epicgames_icon",
        "upc": "ubisoft_icon",
        "searchhost": "search_icon",
        "rockstargames": "rockstar_icon",
        "telegram": "telegram_icon",
        "nvidia app": "nvidia_app_icon",
        "copilot": "copilot_icon",
        "nvidia overlay": "nvidia_app_icon",
        "calculator": "calculator_icon",
        "photos": "photos_icon",
        "idle": "idle_icon",
        "youtube": "youtube_icon",
        "amazon music": "amazonmusic_icon",
        "netplwiz": "netplwiz_icon",
        "taskmgr": "taskmgr_icon",
        "mspaint": "mspaint_icon",
        "windowsterminal": "windowsterminal_icon",
        "excel": "excel_icon",
        "winword": "winword_icon",
        "powerpnt": "powerpnt_icon",
        "unknown": "default_icon",
    }
